s1='''>P00846 RecName: Full=ATP synthase subunit a; AltName: Full=F-ATPase protein 6;
MNENLFASFIAPTILGLPAAVLIILFPPLLIPTSKYLINNRLITTQQWLIKLTSKQMMTMHNTKGRTWSLMLVSLIIFIATTNLLGLLPHSFTPTTQLSMNLAMAIPLWAGTVIMGFRSKIKNALAHFLPQGTPTPLIPMLVIIETISLLIQPMALAVRLTANITAGHLLMHLIGSATLAMSTINLPSTLIIFTILILLTILEIAVALIQAYVFTLLVSLYLHDNT'''
s2='''>P33507 RecName: Full=ATP synthase subunit a; AltName: Full=F-ATPase protein 6;
MMTNLFSVFDPSTTILNLSLNWLSTFLGLLLIPFSFWLLPNRFQVVWNNILLTLHKEFKTLLGPSGHNGSTLMFISLFSLIMFNNFLGLFPYIFTSTSHLTLTLALAFPLWLSFMLYGWINHTQHMFAHLVPQGTPPVLMPFMVCIETISNVIRPGTLAVRLTANMIAGHLLLTLLGNTGPMTTNYIILSLILTTQIALLVLESAVAIIQSYVFAVLSTLYSSEVN'''
name1=s1[1:7]
name2=s2[1:7]
s1=s1.split(';')[2]
s2=s2.split(';')[2]

lenght=0
sequence=''

for i in range(len(s1)):
    for j in range(i,len(s1)):
        if s1[i:j] in s2 and len(s1[i:j])>lenght:
            lenght = len(s1[i:j])
            sequence = s1[i:j]
            
print(lenght,sequence)