---
title: "Lorenz, Pascal, 17-705-187, Group 14, Exercise 1"
author: "Pascal Lorenz"
date: "March 5, 2018"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Task 1
```{r}
#initialize s and z
z <- 3
s <- 2:5 #alternative: seq(2,5)

z*s #multiply each entry of s with z
s[z] #post z-th entry of s
```

Task 2
```{r}
#read table and save as dat
dat <- read.table("http://stat.ethz.ch/Teaching/Datasets/milben.dat", header=TRUE)

summary(dat) #view information about the just downloaded table
```

Task 3
```{r}
dat$n #call entries of 'n', alterative: dat[,1]
sum(dat$n) #sum up entries of 'n'
```

Task 4
```{r}
dat$frequency[dat$n>4] #post all entries of 'frequency' whose corresponding entries in 'n' (entries at same position in matrix) are larger than 4
```

Task 5
```{r}
dat$n[dat$frequency>=9 & dat$frequency<=30] #post all entries of 'n' whose corresponding entries in 'frequency' are in the interval [9,30]

```

